### ISSUE TITLE
VQGAN Configuration for CPDM training

### ISSUE THREAD

**Issue by Bhavik-Ardeshna** [thanhhff/CPDM#3]
Hi @thanhhff @tien-th 

I want to train the VQGAN model using https://github.com/CompVis/taming-transformers repository. I want to know the method you follow to train the VQGAN model. 

Do we need to train on CT images or both CT & PET images? 

All other parameters are the same as those mentioned in the taming-transformer library. If you could guide me in this step with some steps or information, it would help me train the model.

Thanks.

**Comment by thanhhff** [comment]
Dear @Bhavik-Ardeshna,

> Do we need to train on CT images or both CT & PET images?

You should train on both CT&PET images for the encoder and decoder. 

> All other parameters are the same as those mentioned in the taming-transformer library. 

Yes, we used the same parameters as in the original implementation.

For more details, feel free to directly email @tien-th  (tienhuu060102 [at] gmail.com).
Thank you.

**Comment by cuopbiensaysong** [comment]
Hello @Bhavik-Ardeshna  
I only scale the CT and PET data to range [-1, 1] and train VQGAN model using https://github.com/CompVis/taming-transformers repository with following configuration: 

```yaml
model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [1,2,4]  #!!python/tuple
  
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      # target: torch.nn.Identity
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 1000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: ./train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params: 
        test_images_list_file: ./test.txt
        size: 256
```
